// src/config/screenRegistry.js - ARVDOUL CENTRAL SCREEN REGISTRY & PLATFORM CONTRACTS
// Authoritative directory of all application screens, routes, permissions, and data dependencies.

export const SCREEN_REGISTRY = {
  // ========== AUTH & ONBOARDING ==========
  splash: {
    id: 'splash',
    title: 'Splash Screen',
    route: '/',
    auth: 'public',
    permissions: [],
    states: ['loading', 'ready'],
    collections: [],
    mutations: [],
    offlineSupported: true,
    category: 'auth'
  },
  intro: {
    id: 'intro',
    title: 'Intro & Welcome',
    route: '/intro',
    auth: 'public',
    permissions: [],
    states: ['idle', 'ready'],
    collections: [],
    mutations: [],
    offlineSupported: true,
    category: 'auth'
  },
  login: {
    id: 'login',
    title: 'Sign In',
    route: '/login',
    auth: 'public',
    permissions: [],
    states: ['idle', 'authenticating', 'error'],
    collections: ['users'],
    mutations: ['sign_in'],
    offlineSupported: false,
    category: 'auth'
  },
  signupStep1: {
    id: 'signupStep1',
    title: 'Sign Up - Personal Info',
    route: '/signup/step1',
    auth: 'public',
    permissions: [],
    states: ['idle', 'submitting', 'error'],
    collections: ['users'],
    mutations: ['create_account_step1'],
    offlineSupported: false,
    category: 'auth'
  },
  signupStep2: {
    id: 'signupStep2',
    title: 'Sign Up - Verify Contact',
    route: '/signup/step2',
    auth: 'public',
    permissions: [],
    states: ['idle', 'submitting', 'error'],
    collections: ['users'],
    mutations: ['create_account_step2'],
    offlineSupported: false,
    category: 'auth'
  },
  otpVerification: {
    id: 'otpVerification',
    title: 'OTP Verification',
    route: '/otp-verification',
    auth: 'public',
    permissions: [],
    states: ['idle', 'verifying', 'resending', 'error'],
    collections: ['users'],
    mutations: ['verify_otp'],
    offlineSupported: false,
    category: 'auth'
  },
  verifyEmail: {
    id: 'verifyEmail',
    title: 'Verify Email',
    route: '/verify-email',
    auth: 'public',
    permissions: [],
    states: ['idle', 'checking', 'error'],
    collections: ['users'],
    mutations: ['resend_email_verification'],
    offlineSupported: false,
    category: 'auth'
  },
  forgotPassword: {
    id: 'forgotPassword',
    title: 'Forgot Password',
    route: '/forgot-password',
    auth: 'public',
    permissions: [],
    states: ['idle', 'sending', 'sent', 'error'],
    collections: [],
    mutations: ['send_password_reset'],
    offlineSupported: false,
    category: 'auth'
  },
  resetPassword: {
    id: 'resetPassword',
    title: 'Reset Password',
    route: '/reset-password',
    auth: 'public',
    permissions: [],
    states: ['idle', 'resetting', 'completed', 'error'],
    collections: [],
    mutations: ['confirm_password_reset'],
    offlineSupported: false,
    category: 'auth'
  },
  setupProfile: {
    id: 'setupProfile',
    title: 'Setup Profile',
    route: '/setup-profile',
    auth: 'public',
    permissions: ['user'],
    states: ['idle', 'uploading_avatar', 'saving', 'error'],
    collections: ['users'],
    mutations: ['complete_profile_setup'],
    offlineSupported: false,
    category: 'auth'
  },

  // ========== CORE SOCIAL & MEDIA ==========
  home: {
    id: 'home',
    title: 'Home Feed',
    route: '/home',
    auth: 'required',
    permissions: ['user'],
    states: ['idle', 'loading', 'loaded', 'empty', 'error', 'offline'],
    collections: ['posts', 'stories', 'users'],
    mutations: ['create_post', 'like_post', 'comment_post', 'share_post'],
    offlineSupported: true,
    category: 'core'
  },
  videos: {
    id: 'videos',
    title: 'Watch & Reels Feed',
    route: '/videos',
    auth: 'required',
    permissions: ['user'],
    states: ['idle', 'loading', 'loaded', 'empty', 'error'],
    collections: ['posts', 'videos'],
    mutations: ['like_video', 'comment_video', 'tip_creator'],
    offlineSupported: true,
    category: 'core'
  },
  reels: {
    id: 'reels',
    title: 'Fullscreen Reels',
    route: '/reels',
    auth: 'required',
    permissions: ['user'],
    states: ['idle', 'loading', 'loaded', 'error'],
    collections: ['posts'],
    mutations: ['like_video', 'double_tap_like'],
    offlineSupported: true,
    category: 'media'
  },
  videoDetail: {
    id: 'videoDetail',
    title: 'Video Detail Player',
    route: '/video/:videoId',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'playing', 'paused', 'error'],
    collections: ['posts'],
    mutations: ['like_video', 'comment_video'],
    offlineSupported: true,
    category: 'media'
  },
  postDetails: {
    id: 'postDetails',
    title: 'Post Details & Comments',
    route: '/post/:postId',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded', 'error'],
    collections: ['posts', 'comments'],
    mutations: ['add_comment', 'like_post'],
    offlineSupported: true,
    category: 'core'
  },
  createPost: {
    id: 'createPost',
    title: 'Create Post & Reel',
    route: '/create-post',
    auth: 'required',
    permissions: ['user'],
    states: ['idle', 'uploading', 'submitting', 'error'],
    collections: ['posts'],
    mutations: ['publish_post'],
    offlineSupported: true,
    category: 'creation'
  },
  createStory: {
    id: 'createStory',
    title: 'Create Ephemeral Story',
    route: '/create-story',
    auth: 'required',
    permissions: ['user', 'camera', 'microphone'],
    states: ['idle', 'capturing', 'publishing', 'error'],
    collections: ['stories'],
    mutations: ['publish_story'],
    offlineSupported: false,
    category: 'creation'
  },
  stories: {
    id: 'stories',
    title: 'Stories Viewer',
    route: '/stories',
    auth: 'required',
    permissions: ['user'],
    states: ['viewing', 'paused', 'reacting'],
    collections: ['stories'],
    mutations: ['view_story', 'react_story'],
    offlineSupported: true,
    category: 'media'
  },

  // ========== MESSAGING & COMMUNICATIONS ==========
  messaging: {
    id: 'messaging',
    title: 'Messages & Direct Chats',
    route: '/messages',
    auth: 'required',
    permissions: ['user'],
    states: ['idle', 'loading', 'loaded', 'empty', 'error', 'offline'],
    collections: ['conversations', 'messages'],
    mutations: ['send_message', 'create_conversation', 'delete_message'],
    offlineSupported: true,
    category: 'social'
  },
  newConversation: {
    id: 'newConversation',
    title: 'New Conversation',
    route: '/messages/new',
    auth: 'required',
    permissions: ['user'],
    states: ['idle', 'searching_users', 'creating'],
    collections: ['users', 'conversations'],
    mutations: ['start_conversation'],
    offlineSupported: false,
    category: 'social'
  },
  chat: {
    id: 'chat',
    title: 'Chat Session',
    route: '/messages/:conversationId',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'active', 'sending', 'error', 'offline'],
    collections: ['messages'],
    mutations: ['send_text', 'send_media', 'send_voice', 'read_receipt'],
    offlineSupported: true,
    category: 'social'
  },
  groupInfo: {
    id: 'groupInfo',
    title: 'Group Info & Members',
    route: '/messages/:conversationId/info',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded', 'modifying'],
    collections: ['conversations'],
    mutations: ['add_member', 'remove_member', 'leave_group'],
    offlineSupported: true,
    category: 'social'
  },
  conversationSettings: {
    id: 'conversationSettings',
    title: 'Conversation Settings',
    route: '/messages/:conversationId/settings',
    auth: 'required',
    permissions: ['user'],
    states: ['loaded', 'updating'],
    collections: ['conversations'],
    mutations: ['mute_chat', 'block_user', 'clear_history'],
    offlineSupported: true,
    category: 'social'
  },
  call: {
    id: 'call',
    title: 'Voice & Video Calling',
    route: '/call/:conversationId',
    auth: 'required',
    permissions: ['user', 'camera', 'microphone'],
    states: ['connecting', 'connected', 'ended', 'failed'],
    collections: ['calls'],
    mutations: ['start_call', 'end_call', 'toggle_mute', 'toggle_video'],
    offlineSupported: false,
    category: 'social'
  },
  gift: {
    id: 'gift',
    title: 'Send Creator Gift',
    route: '/gift/:userId',
    auth: 'required',
    permissions: ['user'],
    states: ['idle', 'selecting_gift', 'sending', 'success', 'error'],
    collections: ['gift_transactions', 'users'],
    mutations: ['send_gift'],
    offlineSupported: false,
    category: 'monetization'
  },

  // ========== PROFILE & SOCIAL GRAPH ==========
  profileMy: {
    id: 'profileMy',
    title: 'My Profile',
    route: '/profile/me',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded', 'error'],
    collections: ['users', 'posts', 'highlights'],
    mutations: ['edit_bio', 'update_avatar'],
    offlineSupported: true,
    category: 'profile'
  },
  profilePublic: {
    id: 'profilePublic',
    title: 'User Profile',
    route: '/profile/public/:userId',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded', 'error'],
    collections: ['users', 'posts'],
    mutations: ['follow_user', 'unfollow_user', 'block_user'],
    offlineSupported: true,
    category: 'profile'
  },
  editProfile: {
    id: 'editProfile',
    title: 'Edit Profile',
    route: '/profile/edit',
    auth: 'required',
    permissions: ['user'],
    states: ['idle', 'saving', 'error'],
    collections: ['users'],
    mutations: ['update_profile'],
    offlineSupported: true,
    category: 'profile'
  },
  creatorDashboard: {
    id: 'creatorDashboard',
    title: 'Creator Analytics & Dashboard',
    route: '/profile/analytics',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded'],
    collections: ['profile_analytics', 'user_daily_stats'],
    mutations: [],
    offlineSupported: true,
    category: 'creator_suite'
  },
  followers: {
    id: 'followers',
    title: 'Followers List',
    route: '/profile/:userId/followers',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded', 'empty'],
    collections: ['follows'],
    mutations: ['remove_follower'],
    offlineSupported: true,
    category: 'social'
  },
  following: {
    id: 'following',
    title: 'Following List',
    route: '/profile/:userId/following',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded', 'empty'],
    collections: ['follows'],
    mutations: ['unfollow_user'],
    offlineSupported: true,
    category: 'social'
  },
  friends: {
    id: 'friends',
    title: 'Friends & Mutuals',
    route: '/profile/:userId/friends',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded', 'empty'],
    collections: ['friend_requests', 'follows'],
    mutations: ['accept_friend', 'reject_friend'],
    offlineSupported: true,
    category: 'social'
  },
  highlights: {
    id: 'highlights',
    title: 'Story Highlights',
    route: '/profile/highlights',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded'],
    collections: ['highlights'],
    mutations: ['create_highlight', 'delete_highlight'],
    offlineSupported: true,
    category: 'profile'
  },
  about: {
    id: 'about',
    title: 'About Profile & Trust Badges',
    route: '/profile/about',
    auth: 'required',
    permissions: ['user'],
    states: ['loaded'],
    collections: ['users'],
    mutations: [],
    offlineSupported: true,
    category: 'profile'
  },
  profileSettings: {
    id: 'profileSettings',
    title: 'Profile Settings',
    route: '/profile/settings',
    auth: 'required',
    permissions: ['user'],
    states: ['loaded', 'saving'],
    collections: ['user_settings'],
    mutations: ['save_profile_settings'],
    offlineSupported: true,
    category: 'profile'
  },
  network: {
    id: 'network',
    title: 'Network & Suggestions',
    route: '/network',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded'],
    collections: ['users', 'follows'],
    mutations: ['follow_user'],
    offlineSupported: true,
    category: 'social'
  },

  // ========== ADVANCED CREATOR SUITE ==========
  aiStudio: {
    id: 'aiStudio',
    title: 'AI Creative Co-Pilot Studio',
    route: '/ai-studio',
    auth: 'required',
    permissions: ['user'],
    states: ['idle', 'prompting', 'generating', 'completed', 'error'],
    collections: ['ai_creations', 'user_preferences'],
    mutations: ['generate_script', 'generate_caption', 'optimize_video'],
    offlineSupported: false,
    category: 'advanced'
  },
  spaces: {
    id: 'spaces',
    title: 'Live Audio Spaces',
    route: '/spaces',
    auth: 'required',
    permissions: ['user', 'microphone'],
    states: ['idle', 'joining', 'active_room', 'speaking', 'error'],
    collections: ['spaces'],
    mutations: ['join_space', 'raise_hand', 'send_reaction', 'tip_speaker'],
    offlineSupported: false,
    category: 'live'
  },
  sounds: {
    id: 'sounds',
    title: 'Viral Sounds & Music Discovery',
    route: '/sounds',
    auth: 'required',
    permissions: ['user'],
    states: ['idle', 'playing', 'previewing', 'favorited'],
    collections: ['sounds'],
    mutations: ['use_sound', 'save_sound', 'upload_sound'],
    offlineSupported: true,
    category: 'media'
  },
  marketplace: {
    id: 'marketplace',
    title: 'Creator Digital Marketplace',
    route: '/marketplace',
    auth: 'required',
    permissions: ['user'],
    states: ['idle', 'loading', 'loaded', 'purchasing', 'purchased'],
    collections: ['marketplace_items', 'marketplace_orders'],
    mutations: ['buy_item', 'publish_item', 'rate_item'],
    offlineSupported: false,
    category: 'monetization'
  },
  polls: {
    id: 'polls',
    title: 'Community Polls & Prediction Markets',
    route: '/polls',
    auth: 'required',
    permissions: ['user'],
    states: ['idle', 'loading', 'voted', 'staked', 'error'],
    collections: ['polls', 'prediction_markets'],
    mutations: ['vote_poll', 'place_prediction_bet', 'create_poll'],
    offlineSupported: true,
    category: 'community'
  },
  videoEditor: {
    id: 'videoEditor',
    title: 'Multi-Track Video Studio',
    route: '/video-editor',
    auth: 'required',
    permissions: ['user', 'camera', 'microphone'],
    states: ['idle', 'editing', 'rendering', 'exporting'],
    collections: ['drafts'],
    mutations: ['save_draft', 'export_video', 'add_audio_layer'],
    offlineSupported: true,
    category: 'creator_suite'
  },
  audioEditor: {
    id: 'audioEditor',
    title: 'Audio & Podcast Editor',
    route: '/audio-editor',
    auth: 'required',
    permissions: ['user', 'microphone'],
    states: ['idle', 'recording', 'trimming', 'exporting'],
    collections: ['sounds'],
    mutations: ['record_audio', 'add_fx', 'export_audio'],
    offlineSupported: true,
    category: 'creator_suite'
  },
  thumbnailDesigner: {
    id: 'thumbnailDesigner',
    title: 'Thumbnail & Image Studio',
    route: '/thumbnail-designer',
    auth: 'required',
    permissions: ['user'],
    states: ['idle', 'designing', 'exporting'],
    collections: [],
    mutations: ['export_image'],
    offlineSupported: true,
    category: 'creator_suite'
  },
  videoAnalytics: {
    id: 'videoAnalytics',
    title: 'Video Performance Analytics',
    route: '/video-analytics',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded'],
    collections: ['post_analytics'],
    mutations: [],
    offlineSupported: true,
    category: 'creator_suite'
  },

  // ========== COMMUNITY & EVENTS ==========
  communityDirectory: {
    id: 'communityDirectory',
    title: 'Community Directory',
    route: '/community',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded'],
    collections: ['communities'],
    mutations: ['join_community'],
    offlineSupported: true,
    category: 'community'
  },
  createCommunity: {
    id: 'createCommunity',
    title: 'Create Community',
    route: '/community/create',
    auth: 'required',
    permissions: ['user'],
    states: ['idle', 'creating', 'error'],
    collections: ['communities'],
    mutations: ['publish_community'],
    offlineSupported: false,
    category: 'community'
  },
  communityDetail: {
    id: 'communityDetail',
    title: 'Community Feed & Discussion',
    route: '/community/:communityId',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded'],
    collections: ['communities'],
    mutations: ['post_in_community'],
    offlineSupported: true,
    category: 'community'
  },
  communitySettings: {
    id: 'communitySettings',
    title: 'Community Management & Settings',
    route: '/community/:communityId/settings',
    auth: 'required',
    permissions: ['user'],
    states: ['loaded', 'updating'],
    collections: ['communities'],
    mutations: ['update_community_rules'],
    offlineSupported: false,
    category: 'community'
  },
  eventDiscovery: {
    id: 'eventDiscovery',
    title: 'Events Discovery',
    route: '/event',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded'],
    collections: ['events'],
    mutations: ['rsvp_event'],
    offlineSupported: true,
    category: 'events'
  },
  createEvent: {
    id: 'createEvent',
    title: 'Create Event',
    route: '/event/create',
    auth: 'required',
    permissions: ['user'],
    states: ['idle', 'creating', 'error'],
    collections: ['events'],
    mutations: ['publish_event'],
    offlineSupported: false,
    category: 'events'
  },
  eventDetail: {
    id: 'eventDetail',
    title: 'Event Details & RSVP',
    route: '/event/:eventId',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded'],
    collections: ['events'],
    mutations: ['toggle_rsvp'],
    offlineSupported: true,
    category: 'events'
  },

  // ========== COLLABORATION & REPUTATION ==========
  projectDashboard: {
    id: 'projectDashboard',
    title: 'Creator Collaborations Hub',
    route: '/collaboration',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded'],
    collections: ['collaboration_projects'],
    mutations: ['create_project'],
    offlineSupported: true,
    category: 'collaboration'
  },
  projectDetail: {
    id: 'projectDetail',
    title: 'Collaboration Workspace',
    route: '/collaboration/:projectId',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded'],
    collections: ['collaboration_projects'],
    mutations: ['add_collaborator', 'update_task'],
    offlineSupported: true,
    category: 'collaboration'
  },
  rankings: {
    id: 'rankings',
    title: 'Creator Leaderboards & Reputation',
    route: '/rankings',
    auth: 'required',
    permissions: ['user'],
    states: ['idle', 'loading', 'loaded'],
    collections: ['users', 'reputations', 'badges'],
    mutations: ['claim_badge', 'endorse_creator'],
    offlineSupported: true,
    category: 'community'
  },
  badges: {
    id: 'badges',
    title: 'Earned Badges & Milestones',
    route: '/badges',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded'],
    collections: ['badges', 'user_badges'],
    mutations: ['display_badge_on_profile'],
    offlineSupported: true,
    category: 'community'
  },
  reputation: {
    id: 'reputation',
    title: 'Trust & Reputation Score',
    route: '/reputation/:userId',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded'],
    collections: ['reputations'],
    mutations: [],
    offlineSupported: true,
    category: 'community'
  },

  // ========== ADMINISTRATION & MODERATION ==========
  adminDashboard: {
    id: 'adminDashboard',
    title: 'Admin Control Center',
    route: '/admin',
    auth: 'required',
    permissions: ['admin'],
    states: ['idle', 'loading', 'loaded', 'action_in_progress'],
    collections: ['users', 'posts', 'moderation_logs', 'user_reports'],
    mutations: ['ban_user', 'delete_reported_content', 'approve_appeal'],
    offlineSupported: false,
    category: 'administration'
  },
  adminUserManagement: {
    id: 'adminUserManagement',
    title: 'Admin User Management',
    route: '/admin/users',
    auth: 'required',
    permissions: ['admin'],
    states: ['loading', 'loaded'],
    collections: ['users'],
    mutations: ['suspend_user', 'grant_admin', 'revoke_admin'],
    offlineSupported: false,
    category: 'administration'
  },
  adminContentManagement: {
    id: 'adminContentManagement',
    title: 'Admin Content Management',
    route: '/admin/content',
    auth: 'required',
    permissions: ['admin'],
    states: ['loading', 'loaded'],
    collections: ['posts', 'comments'],
    mutations: ['delete_content', 'feature_post'],
    offlineSupported: false,
    category: 'administration'
  },
  adminModerationQueue: {
    id: 'adminModerationQueue',
    title: 'Admin Moderation Queue',
    route: '/admin/moderation',
    auth: 'required',
    permissions: ['admin'],
    states: ['loading', 'loaded'],
    collections: ['comment_reports', 'user_reports', 'moderation_logs'],
    mutations: ['resolve_report', 'dismiss_report'],
    offlineSupported: false,
    category: 'administration'
  },

  // ========== UTILITIES, SETTINGS & RELIABILITY ==========
  coins: {
    id: 'coins',
    title: 'Coin Wallet & Transactions',
    route: '/coins',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded'],
    collections: ['coin_transactions', 'users'],
    mutations: ['purchase_coins', 'transfer_coins'],
    offlineSupported: false,
    category: 'monetization'
  },
  subscription: {
    id: 'subscription',
    title: 'Creator Plus Subscriptions',
    route: '/subscription',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded', 'subscribing'],
    collections: ['subscriptions'],
    mutations: ['subscribe_tier', 'cancel_subscription'],
    offlineSupported: false,
    category: 'monetization'
  },
  notifications: {
    id: 'notifications',
    title: 'Notifications Center',
    route: '/notifications',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded', 'empty'],
    collections: ['notifications'],
    mutations: ['mark_read', 'clear_notifications'],
    offlineSupported: true,
    category: 'social'
  },
  settings: {
    id: 'settings',
    title: 'App Settings & Privacy',
    route: '/settings',
    auth: 'required',
    permissions: ['user'],
    states: ['loaded', 'updating'],
    collections: ['user_settings'],
    mutations: ['update_settings'],
    offlineSupported: true,
    category: 'utility'
  },
  dataUsage: {
    id: 'dataUsage',
    title: 'Data & Storage Usage',
    route: '/settings/data-usage',
    auth: 'required',
    permissions: ['user'],
    states: ['loaded'],
    collections: [],
    mutations: ['clear_cache'],
    offlineSupported: true,
    category: 'utility'
  },
  search: {
    id: 'search',
    title: 'Global Search & Discovery',
    route: '/search',
    auth: 'required',
    permissions: ['user'],
    states: ['idle', 'searching', 'results', 'empty'],
    collections: ['users', 'posts', 'sounds'],
    mutations: [],
    offlineSupported: true,
    category: 'core'
  },
  saved: {
    id: 'saved',
    title: 'Saved Bookmarks',
    route: '/saved',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded', 'empty'],
    collections: ['collections'],
    mutations: ['unsave_post'],
    offlineSupported: true,
    category: 'core'
  },
  collections: {
    id: 'collections',
    title: 'Saved Collections & Folders',
    route: '/collections',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded'],
    collections: ['collections'],
    mutations: ['create_collection', 'delete_collection'],
    offlineSupported: true,
    category: 'core'
  },
  live: {
    id: 'live',
    title: 'Live Video Broadcasts',
    route: '/live',
    auth: 'required',
    permissions: ['user', 'camera', 'microphone'],
    states: ['idle', 'broadcasting', 'viewing', 'error'],
    collections: ['live_streams', 'live_comments'],
    mutations: ['start_broadcast', 'send_live_comment'],
    offlineSupported: false,
    category: 'live'
  },
  offline: {
    id: 'offline',
    title: 'Offline Status & Local Queue',
    route: '/offline',
    auth: 'public',
    permissions: [],
    states: ['loaded'],
    collections: [],
    mutations: ['retry_sync', 'clear_queue'],
    offlineSupported: true,
    category: 'reliability'
  },
  conflicts: {
    id: 'conflicts',
    title: 'Sync Conflict Resolution Matrix',
    route: '/conflicts',
    auth: 'required',
    permissions: ['user'],
    states: ['idle', 'resolving', 'resolved'],
    collections: [],
    mutations: ['resolve_conflict'],
    offlineSupported: true,
    category: 'reliability'
  },
  creatorPayout: {
    id: 'creatorPayout',
    title: 'Creator Earnings & Payout Requests',
    route: '/creator-payout',
    auth: 'required',
    permissions: ['user'],
    states: ['loading', 'loaded', 'requesting'],
    collections: ['withdrawal_requests', 'payout_settings'],
    mutations: ['request_payout', 'update_payout_method'],
    offlineSupported: false,
    category: 'monetization'
  },
  menu: {
    id: 'menu',
    title: 'App Hub & Navigation Menu',
    route: '/menu',
    auth: 'required',
    permissions: ['user'],
    states: ['loaded'],
    collections: [],
    mutations: [],
    offlineSupported: true,
    category: 'utility'
  },
  notFound: {
    id: 'notFound',
    title: 'Page Not Found',
    route: '/404',
    auth: 'public',
    permissions: [],
    states: ['loaded'],
    collections: [],
    mutations: [],
    offlineSupported: true,
    category: 'utility'
  }
};

/**
 * Helper to retrieve screen configuration by route
 */
export function getScreenByRoute(route) {
  return Object.values(SCREEN_REGISTRY).find(s => s.route === route) || null;
}

export default SCREEN_REGISTRY;

